package `in`.kaligotla.allpermissionsimpl.core

import `in`.kaligotla.allpermissionsimpl.R
import `in`.kaligotla.allpermissionsimpl.navigation.MainNavOption
import `in`.kaligotla.allpermissionsimpl.ui.components.appdrawer.AppDrawerItemInfo

object DrawerParams {
    val drawerButtons = arrayListOf(
        AppDrawerItemInfo(
            MainNavOption.MyHome,
            R.string.drawer_home,
            R.drawable.ic_home,
            R.string.drawer_home_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyBodySensors,
            R.string.drawer_body_sensors,
            R.drawable.ic_body_sensors,
            R.string.drawer_body_sensors_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyCalendar,
            R.string.drawer_calendar,
            R.drawable.ic_calendar,
            R.string.drawer_calendar_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyCallLogs,
            R.string.drawer_call_logs,
            R.drawable.ic_call_logs,
            R.string.drawer_call_logs_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyCamera,
            R.string.drawer_camera,
            R.drawable.ic_camera,
            R.string.drawer_camera_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyContacts,
            R.string.drawer_contacts,
            R.drawable.ic_contacts,
            R.string.drawer_contacts_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyLocation,
            R.string.drawer_location,
            R.drawable.ic_location,
            R.string.drawer_location_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyMicrophone,
            R.string.drawer_microphone,
            R.drawable.ic_microphone,
            R.string.drawer_microphone_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyMusicAudio,
            R.string.drawer_music_audio,
            R.drawable.ic_music_audio,
            R.string.drawer_music_audio_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyNearbyDevices,
            R.string.drawer_nearby_devices,
            R.drawable.ic_nearby_devices,
            R.string.drawer_nearby_devices_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyNotifications,
            R.string.drawer_notifications,
            R.drawable.ic_work_notification,
            R.string.drawer_notifications_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyPhone,
            R.string.drawer_phone,
            R.drawable.ic_phone,
            R.string.drawer_phone_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyPhotosVideos,
            R.string.drawer_photos_videos,
            R.drawable.ic_photos_videos,
            R.string.drawer_photos_videos_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyPhysicalActivity,
            R.string.drawer_physical_activity,
            R.drawable.ic_physical_activity,
            R.string.drawer_physical_activity_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MySms,
            R.string.drawer_sms,
            R.drawable.ic_sms,
            R.string.drawer_sms_description
        ),
        AppDrawerItemInfo(
            MainNavOption.MyBiometrics,
            R.string.drawer_biometrics,
            R.drawable.ic_biometrics,
            R.string.drawer_biometrics_description
        ),
        AppDrawerItemInfo(
            MainNavOption.SettingsScreen,
            R.string.drawer_settings,
            R.drawable.ic_settings,
            R.string.drawer_settings_description
        ),
        AppDrawerItemInfo(
            MainNavOption.AboutScreen,
            R.string.drawer_about,
            R.drawable.ic_info,
            R.string.drawer_info_description
        )
    )
}